source:
  type: trino
  serviceName: trino
  serviceConnection:
    config:
      hostPort: "dlh_trino:8090"
      username: "admin"
      catalog: "iceberg"
  sourceConfig:
    config:
      includeTables: true
      includeViews: true

processor:
  type: metadata

profile:
  type: profiler
  config:
    sampleSize: 1000
    profileSample: true

sink:
  type: metadata-rest
  config:
    apiEndpoint: "http://dlh_openmetadata:8585/api"
    authProvider: "openmetadata"
